# Generated by Django 2.2.4 on 2023-01-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cpassword', models.CharField(max_length=255)),
                ('scope_of_work', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='labour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('contact_num', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('cpassword', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('descriptions', models.CharField(max_length=255)),
                ('required_skills', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField(blank=True)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='App1.company')),
                ('labours', models.ManyToManyField(related_name='positions', to='App1.labour')),
            ],
        ),
    ]
